[package]
name = "hex-patch"
description = """
HexPatch is a binary patcher and editor with terminal user interface (TUI),
it's capable of disassembling instructions and assembling patches. 
It supports a variety of architectures and file formats. 
Also, it can edit remote files via SSH."""
version = "1.4.0"
authors = ["Ettore Ricci"]
edition = "2021"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/Etto48/HexPatch"
keywords = ["reverse-engineering","tui","hex-editor","binary-patching"]
categories = ["command-line-utilities","development-tools"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
bitflags = { version = "2.5", features = ["std"] }
capstone = "0.12"
clap = { version = "4.5", features = ["derive"] }
crossterm = { version = "0.27", features = ["serde"] }
dirs = "5.0"
keystone-engine = "0.1"
macro_rules_attribute = "0.2"
mlua = { version = "0.9", features = ["lua54", "vendored", "serialize"] }
object = "0.36"
pathdiff = "0.2"
pdb = "0.8"
ratatui = { version = "0.26", features = ["serde"] }
regex = "1.10"
russh = "0.43"
russh-keys = "0.43"
russh-sftp = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3.1"
symbolic-demangle = "12.8"
tempfile = "3.10"
tokio = "1.37"
