[package]
name = "hex-patch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
crossterm = "0.27.0"
iced-x86 = "1.21.0"
ratatui = "0.26.1"
unicode-segmentation = "1.11.0"
unicode-width = "0.1.11"
