[package]
name = "hex-patch"
description = """
HexPatch is a binary patcher and editor with terminal user interface (TUI),
it's capable of disassembling instructions and assembling patches. 
It supports a variety of architectures and file formats."""
version = "1.0.1"
authors = ["Ettore Ricci"]
edition = "2021"
readme = "README.md"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capstone = "0.12.0"
clap = { version = "4.5.1", features = ["derive"] }
crossterm = "0.27.0"
dirs = "5.0.1"
keystone-engine = "0.1.0"
object = "0.35.0"
pathdiff = "0.2.1"
pdb = "0.8.0"
ratatui = { version = "0.26.2", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
shellexpand = "3.1.0"
symbolic-demangle = "12.8.0"
tempfile = "3.10.1"
