[package]
name = "hex-patch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
crossterm = "0.27.0"
iced-x86 = { version = "1.21.0", features = ["code_asm"] }
ratatui = "0.26.1"
