name: HexPatch
logo: /assets/logo.svg
theme: jekyll-theme-minimal
markdown: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"