name: HexPatch
logo: /assets/logo.svg
theme: jekyll-theme-minimal
markdown: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

docs:
  - title: Home
    url: /
  - title: Plugins API
    url: /plugins_api
  